### ISSUE TITLE
Fizzbuzz 구현

### ISSUE THREAD

**Issue by JINJUN941003** [JINJUN941003/fizzbuzz-for-me#1]
## 목표

나 혼자 완성해보는 fizzbuzz

## 요구사항

- 범위: 1 ~ 20 까지의 정수

## Task

 - [x] print "fizz" if its times of 3
 - [x] print itself if its other else
 - [x] print "buzz" if its times of 5
 - [x] print "fizzbuzz" if its times of 15

## Reference

- https://en.wikipedia.org/wiki/Fizz_buzz
